version: '3'

networks:
  review-net:

services:
  review:
    image: brydanny/microservice-reviews
    environment:
      - MONGO_PORT=27018
      - MONGO_HOST=mongo
      - RABBITMQ_URI=amqp://3.131.89.227:5672
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    networks:
       - review-net
  mongo:
    image: mongo:4.4.4
    environment:
      MONGO_INITDB_DATABASE: review-db
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27018:27017
    networks:
      - review-net
    volumes:
      - ./mongo_data:/data/db
